<?xml version="1.0"?>

<robot name="turn_table" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->
  <!--<xacro:include filename="$(find sawyer_robot)/urdf/_materials.urdf.xacro" />-->
  
  <xacro:macro name="turn_table" params="parent *origin  name:=camera  use_nominal_extrinsics:=false">
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d415_cam_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="d415_cam_depth_to_infra2_offset" value="-0.055"/>
    <xacro:property name="d415_cam_depth_to_color_offset" value="0.015"/>

    <!-- The following values model the aluminum peripherial case for the
  	d415 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d415_cam_width" value="0.099"/>
    <xacro:property name="d415_cam_height" value="0.023"/>
    <xacro:property name="d415_cam_depth" value="0.02005"/>
    <xacro:property name="d415_cam_mount_from_center_offset" value="0.00987"/>

    <!-- The following offset is relative the the physical d415 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d415_cam_depth_px" value="${d415_cam_mount_from_center_offset}"/>
    <xacro:property name="d415_cam_depth_py" value="0.020"/>
    <xacro:property name="d415_cam_depth_pz" value="${d415_cam_height/2}"/>

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_bottom_screw_frame" />
    </joint>

    <link name="${name}_bottom_screw_frame"/>

    <joint name="${name}_link_joint" type="continues">
      <origin xyz="0 ${d415_cam_depth_py} ${d415_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${name}_bottom_screw_frame"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	         <mesh filename="package://turn_table_robot/meshes/base_link.STL"/>
        </geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <mesh
          filename="package://turn_table_robot/meshes/base_link.STL" />
      </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <origin xyz="5.47630436823313 0.00445137401296207 0.127274647707627" rpy="0 0 0" />
      <mass value="53" />
      <inertia
        ixx="4.69052174516768"
        ixy="-2.85464416367111E-06"
        ixz="6.14968020065979E-06"
        iyy="11.0842686073968"
        iyz="-1.23849027826522E-05"
        izz="7.82834235009259" />
      </inertial>
    </link>
   <!-- <link name="${name}_rotation">
      <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
	         <mesh filename="package://turn_table_robot/meshes/base_link.STL"/>
        </geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <mesh
          filename="package://turn_table_robot/meshes/base_link.STL" />
      </geometry>
      </collision>
      <inertial>
        <mass value="4.54714819339239" />
        <origin xyz="-9.32587340685131E-14 -9.32032229172819E-14 0.0772872732553641" />
        <inertia 
        ixx="0.0677428262810966"
        ixy="-3.53126796518736E-18"
        ixz="-8.0168446404932E-14"
        iyy="0.0677428262810966"
        iyz="-8.07156753739356E-14"
        izz="0.134697984247435"  />
      </inertial>
    </link>-->
    <!-- Use the nominal extrinsics between camera frames if the calibrated extrinsics aren't being published. e.g. running the device in simulation  -->
  <!-- <xacro:if value="$(arg use_nominal_extrinsics)">
     
      <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${name}_link"/>
        <child link="${name}_depth_frame" />
      </joint>
      <link name="${name}_depth_frame"/>

      <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_depth_frame" />
        <child link="${name}_depth_optical_frame" />
      </joint>
      <link name="${name}_depth_optical_frame"/>-->

      <!-- camera left IR joints and links -->
      <!--<joint name="${name}_infra1_joint" type="fixed">
        <origin xyz="0 ${d415_cam_depth_to_infra1_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra1_frame" />
      </joint>
      <link name="${name}_infra1_frame"/>

      <joint name="${name}_infra1_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_infra1_frame" />
        <child link="${name}_infra1_optical_frame" />
      </joint>
      <link name="${name}_infra1_optical_frame"/>-->

      <!-- camera right IR joints and links -->
     <!-- <joint name="${name}_infra2_joint" type="fixed">
        <origin xyz="0 ${d415_cam_depth_to_infra2_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_infra2_frame" />
      </joint>
      <link name="${name}_infra2_frame"/>

      <joint name="${name}_infra2_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_infra2_frame" />
        <child link="${name}_infra2_optical_frame" />
      </joint>
      <link name="${name}_infra2_optical_frame"/>-->

      <!-- camera color joints and links -->
     <!-- <joint name="${name}_color_joint" type="fixed">
        <origin xyz="0 ${d415_cam_depth_to_color_offset} 0" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_color_frame" />
      </joint>
      <link name="${name}_color_frame"/>

      <joint name="${name}_color_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="${name}_color_frame" />
        <child link="${name}_color_optical_frame" />
      </joint>
      <link name="${name}_color_optical_frame"/>
    </xacro:if>-->
  </xacro:macro>
</robot>
